# Generated by Django 3.2 on 2022-05-03 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderPayment',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('status', models.PositiveSmallIntegerField(choices=[('FAILED', 0), ('WAITING', 1), ('NEED_CONFIRM', 2), ('CONFIRMED', 3)], default=1)),
                ('method', models.CharField(choices=[('CASH', 'Cash'), ('OTHER', 'Other')], default='Cash', max_length=30)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='order.order')),
            ],
            options={
                'db_table': 'order_payments',
                'managed': True,
            },
        ),
    ]
