# Generated by Django 3.2 on 2022-05-03 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('uid', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=150, unique=True)),
                ('role', models.CharField(choices=[('DEVELOPER', 'Developer'), ('OWNER', 'Owner'), ('ADMIN', 'Admin'), ('STAFF', 'Staff'), ('INTERNAL', 'Internal'), ('GUEST', 'Guest')], max_length=30)),
                ('first_name', models.CharField(max_length=75)),
                ('middle_name', models.CharField(blank=True, default=None, max_length=75, null=True)),
                ('last_name', models.CharField(blank=True, default=None, max_length=75, null=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('last_update', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('picture', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='file.file')),
            ],
            options={
                'db_table': 'accounts',
                'managed': True,
            },
        ),
    ]
