# Generated by Django 3.2 on 2022-05-03 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0001_initial'),
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('FOOD', 'Food'), ('BEVERAGE', 'Beverage'), ('OTHER', 'Other')], max_length=30)),
                ('product_type', models.CharField(choices=[('HOT_DRINK', 'Hot Drink'), ('COLD_DRINK', 'Cold Drink'), ('SNACK', 'Snack'), ('DESSERT', 'Dessert'), ('MAIN_COURSE', 'Main Course'), ('OTHER', 'Other')], db_column='type', max_length=50)),
                ('slug', models.SlugField(blank=True, default=None, null=True)),
                ('short_name', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('long_name', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(max_length=3000)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='business.business')),
                ('picture', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='file.file')),
            ],
            options={
                'db_table': 'products',
                'managed': True,
            },
        ),
    ]
