# Generated by Django 3.2 on 2022-05-03 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('before', models.PositiveSmallIntegerField(choices=[('CANCEL', 0), ('UNCONFIRMED', 1), ('IN_QUEUE', 2), ('ONSERVING', 3), ('SERVED', 4), ('PAID', 5), ('COMPLETE', 6)])),
                ('after', models.PositiveSmallIntegerField(choices=[('CANCEL', 0), ('UNCONFIRMED', 1), ('IN_QUEUE', 2), ('ONSERVING', 3), ('SERVED', 4), ('PAID', 5), ('COMPLETE', 6)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account.account')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='order.order')),
            ],
            options={
                'db_table': 'order_status',
                'managed': True,
            },
        ),
    ]
