# Generated by Django 3.2 on 2022-05-03 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('file_type', models.CharField(choices=[('IMAGE', 'Image'), ('OTHER', 'Other')], db_column='type', max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('ext', models.CharField(max_length=10)),
                ('location', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('url', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'files',
                'managed': True,
            },
        ),
    ]
