# Generated by Django 3.2 on 2022-05-03 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('contact_type', models.CharField(choices=[('PHONE', 'Phone'), ('WHATSAPP', 'Whatsapp'), ('EMAIL', 'Email')], db_column='type', max_length=50)),
                ('owner_type', models.CharField(choices=[('USER', 'account'), ('BUSINESS', 'business')], max_length=100)),
                ('owner_ref', models.BigIntegerField(editable=False)),
                ('value', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
            ],
            options={
                'db_table': 'contacts',
                'managed': True,
            },
        ),
    ]
