# Generated by Django 3.2 on 2022-05-03 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('current_status', models.PositiveSmallIntegerField(choices=[('CANCEL', 0), ('UNCONFIRMED', 1), ('IN_QUEUE', 2), ('ONSERVING', 3), ('SERVED', 4), ('PAID', 5), ('COMPLETE', 6)], default=1)),
                ('total_price', models.PositiveBigIntegerField(default=0)),
                ('is_anonym', models.BooleanField(default=False)),
                ('guest_info', models.JSONField()),
                ('note', models.TextField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True, null=True)),
                ('guest', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='account.account')),
            ],
            options={
                'db_table': 'orders',
                'managed': True,
            },
        ),
    ]
